# SonarQube Cloud Project Identification
sonar.projectKey=Nycopaderayon03_March-03-30-2026
sonar.organization=nycopaderayon03
sonar.host.url=https://sonarcloud.io/api/project_badges/measure?project=Nycopaderayon03_March-03-30-2026&metric=alert_status

# Source Folders to Scan (Crucial for your grade!)
# This ensures both your Flutter and PHP code are analyzed
sonar.sources=lib,app

# Files/Folders to Exclude
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
