sonar.projectKey=Nycopaderayon03_March-03-30-2026
sonar.organization=nycopaderayon03
sonar.sources=Services,authentication,sanctiontracker
sonar.exclusions=.venv/**,venv/**,__pycache__/**,logs/**,media/**,staticfiles/**,db.sqlite3,**/migrations/**,**/*.min.js,**/*.min.css


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=March-03-30-2026
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
