# SonarQube Cloud Project Identification
sonar.projectKey=Nycopaderayon03_March-03-30-2026
sonar.organization=Nycopaderayon03
sonar.host.url=https://sonarcloud.io

# Source Folders to Scan (Crucial for your grade!)
# This ensures both your Flutter and PHP code are analyzed
sonar.sources=lib,app

# Files/Folders to Exclude
sonar.exclusions=**/*.g.dart,**/vendor/**,**/node_modules/**
