"""
Django settings for sanctiontracker project.

Generated by 'django-admin startproject'.
"""

from pathlib import Path
import os
import logging
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR_STR = str(BASE_DIR)
logger = logging.getLogger(__name__)

def env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_csv(name: str) -> list[str]:
    return [value.strip() for value in os.environ.get(name, "").split(",") if value.strip()]


DEBUG = env_bool("DEBUG", False)

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    if DEBUG:
        # Local dev fallback only. Never rely on this in production.
        SECRET_KEY = "unsafe-dev-secret-key-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DEBUG is False.")

configured_allowed_hosts = env_csv("ALLOWED_HOSTS")
if configured_allowed_hosts:
    ALLOWED_HOSTS = configured_allowed_hosts
else:
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "web",
        "my-jmc-pod.duckdns.org",
        "jmcedu.duckdns.org",
        "72.62.197.37",
        "143.44.184.72",
    ]

configured_csrf_trusted_origins = env_csv("CSRF_TRUSTED_ORIGINS")
if configured_csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS = configured_csrf_trusted_origins
else:
    CSRF_TRUSTED_ORIGINS = [
        "https://my-jmc-pod.duckdns.org",
        "https://jmcedu.duckdns.org",
    ]


extra_allowed_hosts = [
    host.strip()
    for host in os.environ.get("ADDITIONAL_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]
if extra_allowed_hosts:
    ALLOWED_HOSTS.extend(extra_allowed_hosts)

extra_csrf_trusted_origins = [
    origin.strip()
    for origin in os.environ.get("ADDITIONAL_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
if extra_csrf_trusted_origins:
    CSRF_TRUSTED_ORIGINS.extend(extra_csrf_trusted_origins)

domain_host = (os.environ.get("DOMAIN") or "").strip()
if domain_host:
    ALLOWED_HOSTS.append(domain_host)
    CSRF_TRUSTED_ORIGINS.append(f"https://{domain_host}")

# De-duplicate while preserving order
ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

AUTH_USER_MODEL = 'authentication.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.RateLimitMiddleware',  # Protect against abuse
]

ROOT_URLCONF = 'sanctiontracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR_STR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'authentication.context_processors.admin_notifications',
                'authentication.context_processors.student_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'sanctiontracker.wsgi.application'


# =========================
# Caching (for rate limiting & session management)
# =========================
CACHES = {
    'default': {
        'BACKEND': os.environ.get('CACHE_BACKEND', 'django.core.cache.backends.locmem.LocMemCache'),
        'LOCATION': os.environ.get('CACHE_LOCATION', 'unique-snowflake'),
        'TIMEOUT': int(os.environ.get('CACHE_TIMEOUT', '300')),
        'OPTIONS': {
            'MAX_ENTRIES': int(os.environ.get('CACHE_MAX_ENTRIES', '1000')),
        }
    }
}
# For production, consider using Redis or Memcached


# =========================
# Database
# =========================
DB_ENGINE = (os.environ.get("DB_ENGINE") or "postgresql").strip().lower()

if DB_ENGINE in {"postgres", "postgresql"}:
    db_defaults = {
        "DB_NAME": "sanction_tracker_db",
        "DB_USER": "sanction_user",
        # Never provide a default for secrets; require env injection.
        "DB_PASSWORD": "",
        "DB_HOST": "localhost",
        "DB_PORT": "5432",
    }
    db_config = {key: os.environ.get(key) or default for key, default in db_defaults.items()}
    missing = [key for key, value in db_config.items() if not value]
    if missing:
        raise ImproperlyConfigured(
            "PostgreSQL selected (DB_ENGINE) but missing env vars: " + ", ".join(missing)
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_config["DB_NAME"],
            "USER": db_config["DB_USER"],
            "PASSWORD": db_config["DB_PASSWORD"],
            "HOST": db_config["DB_HOST"],
            "PORT": db_config["DB_PORT"],
        }
    }

elif DB_ENGINE == "sqlite3":
    sqlite_path = os.environ.get("DB_FILE_PATH")
    sqlite_path = Path(sqlite_path) if sqlite_path else (BASE_DIR / "db.sqlite3")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_path,
        }
    }
else:
    raise ImproperlyConfigured(f"Unsupported DB_ENGINE value: {DB_ENGINE}")


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.environ.get("APP_TIME_ZONE", "Asia/Manila")
USE_I18N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR_STR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR_STR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR_STR, 'media')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", True)

# =========================
# API Auth (JWT)
# =========================
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_TOKEN_MINUTES", "30"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_TOKEN_DAYS", "7"))
    ),
    "ROTATE_REFRESH_TOKENS": env_bool("JWT_ROTATE_REFRESH_TOKENS", False),
    "BLACKLIST_AFTER_ROTATION": env_bool("JWT_BLACKLIST_AFTER_ROTATION", False),
    "UPDATE_LAST_LOGIN": env_bool("JWT_UPDATE_LAST_LOGIN", True),
}

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", True)
    # Default to secure cookies in production, but allow local HTTP docker runs to
    # override via env (otherwise auth/CSRF can break on http://localhost).
    SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", SECURE_SSL_REDIRECT)
    CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", SECURE_SSL_REDIRECT)
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", True)
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", True)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = os.environ.get(
        "SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin"
    )

# Basic protection against oversized uploads causing memory pressure.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", "10485760"))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", "5242880"))

# Public base URL used for links generated outside request/response flow
# (for example cron-driven reminder emails).
PUBLIC_BASE_URL = (os.environ.get("PUBLIC_BASE_URL") or "").strip().rstrip("/")
if not PUBLIC_BASE_URL:
    domain_fallback = (os.environ.get("DOMAIN") or "").strip()
    if domain_fallback:
        PUBLIC_BASE_URL = f"https://{domain_fallback}".rstrip("/")

# Move Django admin to a non-standard URL to reduce automated probing.
ADMIN_URL = os.environ.get("DJANGO_ADMIN_PATH", "secure-admin-portal").strip().strip("/")
ADMIN_URL = f"{ADMIN_URL}/"


# =========================
# Email Configuration (Auto-detect Resend vs SMTP)
# =========================

# Support both Resend API and Gmail SMTP (with auto-detection)
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()
SMTP_ENABLED = not RESEND_API_KEY

if RESEND_API_KEY:
    # Use Resend API (modern, better for production)
    EMAIL_BACKEND = "resend.django.backend.EmailBackend"
    logger.info("Using Resend email backend")
    # Resend from email can be set via RESEND_FROM_EMAIL or DEFAULT_FROM_EMAIL
    RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", "").strip()
    # Default to onboarding email if not configured
    if not RESEND_FROM_EMAIL:
        RESEND_FROM_EMAIL = "onboarding@resend.dev"
    DEFAULT_FROM_EMAIL = RESEND_FROM_EMAIL
else:
    # Fallback to Gmail SMTP (legacy)
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").strip().lower() in {"1", "true", "yes", "on"}
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").strip().lower() in {"1", "true", "yes", "on"}
    
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    smtp_default_from_email = os.environ.get("DEFAULT_FROM_EMAIL", "").strip()
    placeholder_from_emails = {
        "noreply@yourcompany.com",
        "no-reply@yourcompany.com",
        "noreply@example.com",
        "no-reply@example.com",
    }
    if not smtp_default_from_email or smtp_default_from_email.lower() in placeholder_from_emails:
        DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or smtp_default_from_email
        if smtp_default_from_email and DEFAULT_FROM_EMAIL != smtp_default_from_email:
            logger.warning(
                "Ignoring placeholder DEFAULT_FROM_EMAIL=%s for SMTP; using EMAIL_HOST_USER instead.",
                smtp_default_from_email,
            )
    else:
        DEFAULT_FROM_EMAIL = smtp_default_from_email
    logger.warning("Using legacy Gmail SMTP. Consider migrating to Resend for better reliability.")

# =========================
# Logging
# =========================
_LOGS_DIR = os.path.join(BASE_DIR_STR, 'logs')
if not os.path.exists(_LOGS_DIR):
    os.makedirs(_LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(_LOGS_DIR, 'django.log'),
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'authentication': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
