# Generated by Django 4.2.11 on 2026-04-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_add_restorative_justice_gravity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='sanction_flow',
            field=models.CharField(choices=[('first_offense', '1st Offense'), ('second_offense', '2nd Offense'), ('third_offense', '3rd Offense'), ('community_service', 'Community Service')], default='community_service', max_length=32),
        ),
    ]
